//connection details - probs move to config file
//export const HOST = '192.168.1.240'
export const HOST = '192.168.1.7' //move property
export const PORT = '136' //move to property
export const API_ADDRESS = '/service'
export const PROTOCOL = 'http'

//queries
export const QUERY = 'query'
export const GET_ALL_STATES = 'getAllStates'
export const GET_ALL_ACTIVITIES = 'getAllActivities'
export const GET_ALL_LOCATIONS = 'getAllLocations'
export const GET_USER_BY_USERNAME = 'getUserByUsername'
export const GET_AVAIL_PLAY_SESSIONS = 'getAvailableSessions'
export const GET_PENDING_PLAY_SESSIONS = 'getPendingSessions'
export const CHECK_SESSION = 'checkSession'
export const SEARCH_USERS = 'searchUsers'

//mutations
export const MUTATION = 'mutation'
export const CREATE_NEW_USER = 'createNewUser'
export const UPDATE_USER = 'updateUser'
export const CREATE_USER_ADDRESS = 'addUserAddress'
export const CREATE_PHONE = 'addPhone'
export const SIGN_IN = 'signIn'
export const SIGN_OUT = 'signOut'
export const ADD_COMMENT = 'addComment'
export const ADD_USER_LEGAL_DOC = 'addUserLegalDoc'
export const RECOVERY_SIGN_IN = 'recoverySignIn'
export const SET_NEW_PASSWORD = 'setNewPassword'
export const ADD_USER_SESSION = 'addUserSession'

//params & fields
export const TYPE = 'type'
export const INPUT_USER = 'inputUser'
export const AUTHDATA = 'authData'
export const EMAILADDRESS = 'emailAddress'
export const USERID = 'userId'
export const TYPE_CODE = 'typeCode'
export const CODE = 'code'
export const ADDRESSID = 'addressId'
export const STATUSID = 'statusId'
export const STATUS = 'status'
export const USERNAME = 'username'
export const PASSWORD = 'password'
export const SECURITYQ = 'securityQuestion'
export const SECURITYA = 'securityAnswer'
export const FIRST_NAME = 'firstName'
export const LAST_NAME = 'lastName'
export const GENDER = 'gender'
export const AGE = 'age'
export const HEIGHT = 'height'
export const WEIGHT = 'weight'
export const IDP = 'idp'
export const EMAIL_VERIFIED = 'emailVerified'
export const PLAYED_BEFORE = 'playedBefore'
export const REAL_ESTATE_SERVICE = 'reServices'
export const LIABLE_AGREE = 'liableAgree'
export const TC_AGREE = 'tcAgree'
export const CAN_CONTACT = 'canContact'
export const TOKEN = 'token'
export const PASSCODE = 'passCode'
export const NAME = 'name'
export const CREATED_DATE = 'createdDate'

export const INPUT_ADDRESS = 'inputAddress'
export const ADDRESS = 'address'
export const STREET = 'street'
export const APT = 'apt'
export const STATE = 'state'
export const STATE_CODE = 'stateCode'
export const STATE_ID = 'stateId'
export const UNIT = 'unit'
export const CITY = 'city'
export const POSTAL_CODE = 'postalCode'

export const INPUT_PHONE = 'inputPhone'
export const PHONEID = 'phoneId'
export const PHONE_COUNTRY_CODE = 'countryCode'
export const NUMBER = 'number'
export const PHONE_NUMBER = 'phoneNum'
export const PHONE_NUMBERS = 'phoneNumbers'

export const INPUT_COMMENT = 'inputComment'
export const COMMENT_CONTENT = 'commentContent'
export const COMMENTID = 'commentId'
export const NEW_LINE_TOKEN = '[LF]'

export const INPUT_LEGAL = 'inputLegal'
export const LEGAL_DOC_ID = 'legalDocId'
export const AGREE = 'agree'
export const ACTIVE_DATE = 'activeDate'
export const EXPIRE_DATE = 'expireDate'
export const ENABLED = 'enabled'

export const ACTIVITY_ID = 'activityId'
export const ACTIVITY_NAME = 'activityName'
export const ACTIVITY = 'activity'

export const LOCATION_ID = 'locationId'
export const LOCATION_NAME = 'locationName'
export const LOCATION = 'location'
export const START_DATE = 'startDate'
export const END_DATE = 'endDate'

export const INPUT_PLAY_SESSION = 'inputPlaySession'
export const PAYED = 'payed'
export const SESSIONID = 'sessionId'
export const COST_PER_MIN = "costpm"
export const SETUP_MINUTES = "setupMin"
export const TAX_RATE = "taxRate"
export const MANAGER = 'manager'